const LOGO_URL = 'https://r2.fivemanage.com/reN0iza3vc4oGjJ0nDgay/DcLogo.png'
function logoIcon(){return `<img src="${LOGO_URL}" alt="Logo" class="w-12 h-12 rounded-lg object-cover flex-shrink-0">`}
let useGradient = false
try{const s=localStorage.getItem('fearx_notify_useGradient');if(s!==null){useGradient = s==='true'}}catch(e){}
function setPosition(pos){const c=document.getElementById('notification-container');if(!c)return;c.className='fixed z-50 flex flex-col space-y-3 transform';if(!pos)pos='top-right';if(pos==='top-right'){c.className+=' top-5 right-5 items-end'}else if(pos==='top-left'){c.className+=' top-5 left-5 items-start'}else if(pos==='bottom-right'){c.className+=' bottom-5 right-5 items-end'}else if(pos==='bottom-left'){c.className+=' bottom-5 left-5 items-start'}else if(pos==='center-right'||pos==='right'){c.className+=' inset-y-0 right-5 justify-center items-end'}else if(pos==='center-left'||pos==='left'){c.className+=' inset-y-0 left-5 justify-center items-start'}else if(pos==='top-center'){c.className+=' top-5 left-1/2 -translate-x-1/2 items-center'}else if(pos==='bottom-center'){c.className+=' bottom-5 left-1/2 -translate-x-1/2 items-center'}else{c.className+=' top-5 right-5 items-end'}}
function playSound(file,volume){if(!file)return;try{let src=file;if(!/^https?:/i.test(file)&&!file.startsWith('/')){src=`sounds/${file}`}const a=new Audio(src);a.volume=Math.max(0,Math.min(1,parseFloat(volume||'0.3')||0.3));a.play().catch(()=>{})}catch(e){}}
function renderNotification(data){const container=document.getElementById('notification-container');if(!container)return;const type=(data.type||'info');const duration=(data.duration||5000);const title=(data.title||(type.charAt(0).toUpperCase()+type.slice(1)));const message=(data.message||data.description||'');const position=data.position;setPosition(position);const icon=logoIcon();let barColor=data.barColor;let barHex=data.barHex||data.color;if(!barColor&&!barHex){if(type==='success')barColor='bg-green-500';else if(type==='error')barColor='bg-red-500';else if(type==='kill')barColor='bg-green-500';else if(type==='killed')barColor='bg-red-500';else barHex='#ef4444'}let countBox='';if(data.count){let countColor=data.countColor;if(!countColor){if(type==='kill')countColor='bg-gradient-to-b from-green-600 to-green-700';else if(type==='killed')countColor='bg-gradient-to-b from-red-600 to-red-700';else countColor='bg-gradient-to-b from-sky-600 to-sky-700'}countBox=`<div class="count-box ${countColor} text-white w-10 h-10 flex items-center justify-center rounded-lg font-black text-lg flex-shrink-0">${data.count}</div>`}const bodyClass = useGradient? 'notification-body red-gradient' : 'notification-body';const barStyle=barHex?`background-color:${barHex};`:'';const barClass=barColor?`${barColor}`:'';const notification=document.createElement('div');notification.className='notification';notification.innerHTML=`
<div class="${bodyClass} w-[360px] rounded-xl flex items-center p-2.5 space-x-3">
<div class="flex-shrink-0">${icon}</div>
<div class="flex-1 overflow-hidden">
<div>
<p class="text-sm text-neutral-300 font-medium truncate">${title}</p>
<h1 class="text-lg text-white font-extrabold truncate">${message}</h1>
</div>
<div class="h-1 bg-black/30 rounded-full overflow-hidden mt-1.5">
<div class="timer-bar h-full ${barClass} rounded-full" style="${barStyle}animation-duration:${duration}ms;"></div>
</div>
</div>
${countBox}
</div>`;container.appendChild(notification);if(data.sound){playSound(data.sound,data.volume)}setTimeout(()=>{notification.classList.add('exit');notification.addEventListener('animationend',()=>notification.remove())},duration)}
function openSettings(){const m=document.getElementById('settings-modal');if(!m)return;const radios=m.querySelectorAll('input[name="grad"]');radios.forEach(r=>{r.checked=(r.value===(useGradient?'on':'off'))});m.classList.add('show')}
function closeSettings(){const m=document.getElementById('settings-modal');if(!m)return;m.classList.remove('show')}
function initSettingsUI(){const modal=document.getElementById('settings-modal');if(!modal)return;const save=document.getElementById('settings-save');const cancel=document.getElementById('settings-cancel');const close=document.getElementById('settings-close');const getChoice=()=>{const sel=modal.querySelector('input[name="grad"]:checked');return sel?sel.value:'on'};const doClose=()=>{closeSettings();fetch(`https://fearx-notify/fearx_notify_settings_close`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).catch(()=>{})};save.addEventListener('click',()=>{useGradient=getChoice()==='on';try{localStorage.setItem('fearx_notify_useGradient',String(useGradient))}catch(e){};fetch(`https://fearx-notify/fearx_notify_settings_save`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({useGradient})}).catch(()=>{});doClose()});cancel.addEventListener('click',doClose);close.addEventListener('click',doClose)}
window.addEventListener('message',(event)=>{if(!event||!event.data)return;const d=event.data;if(d.action==='fearx_notify')renderNotification(d);if(d.action==='fearx_notify_settings_open')openSettings()});
document.addEventListener('DOMContentLoaded',()=>{initSettingsUI()})
